language: python
python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=mftb5.settings.testing

before_install:
  - sudo apt-get install libenchant-dev

install:
  - pip install -r requirements.txt

script:
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - python ./manage.py test
